all:
	make -f ref_cache.mk idx GENOME=human
	make -f ref_cache.mk idx GENOME=mus_musculus
	make -f ref_cache.mk idx GENOME=drosophila_melanogaster
	make -f ref_cache.mk idx GENOME=saccharomyces_cerevisiae
